baseurl = "https://melissagwolf.com/"
languageCode = "en-us"
title = "Melissa G Wolf"
theme = "hugo-xmin"
googleAnalytics = "UA-152937120-3"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 2
[[menu.main]]
    name = "Preprints"
    url = "/preprints/"
    weight = 3
[[menu.main]]
    name = "SPSS to R"
    url = "/spss to r/"
    weight = 4
#[[menu.main]]
    #name = "Subscribe"
    #url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [Melissa G Wolf](https://melissagwolf.com) | [Twitter](https://twitter.com/melissagwolf) | [Github](https://github.com/melissagwolf) | [Contact](mailto:melissagordon@ucsb.edu)"
